const SET_LOADER = 'cat/SET_LOADER'
const SET_ERROR = 'cat/SET_ERROR'
const LOAD_CATS = 'cat/LOAD_CATS'
const SET_BREED = 'cat/SET_BREED'
const RESET_LIMIT = 'cat/RESET_LIMIT'
const SET_SINGLE_BREED = 'cat/SET_SINGLE_BREED'
const SET_LOAD_MORE = 'cat/SET_LOAD_MORE'

export default {
  SET_LOADER,
  SET_ERROR,
  LOAD_CATS,
  SET_BREED,
  RESET_LIMIT,
  SET_SINGLE_BREED,
  SET_LOAD_MORE
}